// <auto-generated />
using System;
using LaytonGenius.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LaytonGenius.Migrations
{
    [DbContext(typeof(AppointmentContext))]
    [Migration("20220323162054_All")]
    partial class All
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("LaytonGenius.Models.Appointment", b =>
                {
                    b.Property<int>("AppId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DateID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("AppId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("LaytonGenius.Models.Available", b =>
                {
                    b.Property<int>("DateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.HasKey("DateID");

                    b.ToTable("AvailableTimes");

                    b.HasData(
                        new
                        {
                            DateID = 1,
                            Date = new DateTime(2022, 3, 23, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DateID = 2,
                            Date = new DateTime(2022, 3, 23, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DateID = 3,
                            Date = new DateTime(2022, 3, 23, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DateID = 4,
                            Date = new DateTime(2022, 3, 23, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DateID = 5,
                            Date = new DateTime(2022, 3, 23, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DateID = 6,
                            Date = new DateTime(2022, 3, 23, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DateID = 7,
                            Date = new DateTime(2022, 3, 23, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DateID = 8,
                            Date = new DateTime(2022, 3, 23, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DateID = 9,
                            Date = new DateTime(2022, 3, 23, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DateID = 10,
                            Date = new DateTime(2022, 3, 23, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DateID = 11,
                            Date = new DateTime(2022, 3, 23, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DateID = 12,
                            Date = new DateTime(2022, 3, 23, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DateID = 13,
                            Date = new DateTime(2022, 3, 23, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
